// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaemnfpwaylxjnzphciw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZW1uZnB3YXlseGpuenBoY2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzY4MDYsImV4cCI6MjA2OTMxMjgwNn0.zz0ZpXf35Qp2nd9ZaINv0nl7Rc7k4zmAE-19YzxC5VU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
